// Stitched v2 — Real product storefront with images
// Architecture: loads products from products.json (fetched at run time),
// falls back to embedded data. Cart/orders in localStorage.

const DATA_URL = 'products.json';

// ─── Data ─────────────────────────────────────────────────────────────
let products = [];
let orders = [];
let cart = [];
let currentPage = 'store';
let lastSync = null;

function ls(key) { try { return localStorage.getItem('st_'+key); } catch { return null; } }
function lss(key, v) { try { localStorage.setItem('st_'+key, v); } catch {} }
function lsj(key, d) {
  try { const r = ls(key); return r ? JSON.parse(r) : d; } catch { return d; }
}
function lssj(key, v) { lss(key, JSON.stringify(v)); }

function notify(m) {
  let e = document.querySelector('.toast');
  if (!e) { e = document.createElement('div'); e.className='toast'; document.body.appendChild(e); }
  e.textContent = m; e.classList.add('show');
  setTimeout(() => e.classList.remove('show'), 3000);
}

function $(s, p) { return (p||document).querySelector(s); }
function $$(s, p) { return [...(p||document).querySelectorAll(s)]; }

// ─── API fetch helpers ────────────────────────────────────────────────
async function fetchJSON(url) {
  try { const r = await fetch(url); return r.ok ? await r.json() : null; }
  catch { return null; }
}

// Build a product from DummyJSON item with dropshipping pricing
function buildProduct(dj) {
  const catMap = {
    'beauty': 'Beauty', 'fragrances': 'Beauty',
    'furniture': 'Home', 'home-decoration': 'Home',
    'groceries': 'Groceries', 'snacks': 'Groceries',
    'electronics': 'Electronics', 'tablets': 'Electronics',
    'smartphones': 'Electronics', 'laptops': 'Electronics',
    'mobile-accessories': 'Accessories',
    'vehicle': 'Accessories', 'motorcycle': 'Accessories',
    'sports-accessories': 'Sports',
    'womens-dresses': 'Clothing', 'womens-shoes': 'Clothing',
    'mens-shirts': 'Clothing', 'mens-shoes': 'Clothing',
    'tops': 'Clothing', 'womens-bags': 'Accessories',
    'womens-watches': 'Accessories', 'mens-watches': 'Accessories',
    'sunglasses': 'Accessories', 'skin-care': 'Beauty',
  };
  const cat = catMap[dj.category] || 'Other';
  const supplierPrice = Math.round(dj.price * 0.4 * 100) / 100;
  const yourPrice = Math.round(dj.price * 1.0 * 100) / 100;
  return {
    id: 'dj_'+dj.id,
    name: dj.title.slice(0, 80),
    supplierPrice,
    yourPrice,
    description: dj.description,
    category: cat,
    supplier: 'AliExpress',
    image: dj.thumbnail,
    images: (dj.images||[dj.thumbnail]).filter(Boolean),
    rating: Math.round((dj.rating||4)*10)/10,
  };
}

// ─── Init ─────────────────────────────────────────────────────────────
async function init() {
  // Load saved state
  products = lsj('products', []);
  orders = lsj('orders', []);
  cart = lsj('cart', []);
  lastSync = ls('lastSync');

  // Try remote products.json (generated by GitHub Actions or embedded)
  let remote = await fetchJSON(DATA_URL);
  if (remote && Array.isArray(remote) && remote.length > 0) {
    products = remote;
    lssj('products', products);
    lastSync = new Date().toISOString();
    lss('lastSync', lastSync);
  }

  // If still empty, fetch from DummyJSON API directly (fallback)
  if (products.length === 0) {
    remote = await fetchJSON('https://dummyjson.com/products?limit=30');
    if (remote && remote.products) {
      products = remote.products.map(buildProduct);
      lssj('products', products);
    }
  }

  render();
}

// ─── Render ───────────────────────────────────────────────────────────
function render() {
  const app = document.getElementById('app');
  app.innerHTML = '';

  // Topbar
  const h = document.createElement('header');
  h.className = 'topbar';
  const cc = cart.reduce((s,i) => s+i.qty, 0);
  h.innerHTML = `<div class="topbar-inner">
    <button class="logo" onclick="nav('store')"><span class="logo-icon">🧵</span><span>Stitched<span class="logo-dot"></span></span></button>
    <nav class="nav">
      <button class="nav-btn ${currentPage==='store'?'active':''}" onclick="nav('store')">Store</button>
      <button class="nav-btn ${currentPage==='admin'?'active':''}" onclick="nav('admin')">Dashboard</button>
    </nav>
    <button class="cart-btn" onclick="cartOpen()">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/></svg>
      Cart
      <span class="cart-badge ${cc===0?'hidden':''}" id="cb">${cc}</span>
    </button>
  </div>`;

  // Page
  const pg = document.createElement('div');
  pg.className = 'page';
  if (currentPage==='store') pg.appendChild(renderStore());
  else if (currentPage==='admin') pg.appendChild(renderDash());
  else if (currentPage==='checkout') pg.appendChild(renderCheckout());
  else if (currentPage==='product') pg.appendChild(renderProduct());
  else if (currentPage==='confirmed') pg.appendChild(renderConfirmed());
  else if (currentPage==='about') pg.appendChild(renderAbout());
  else if (currentPage==='terms') pg.appendChild(renderTerms());
  else if (currentPage==='privacy') pg.appendChild(renderPrivacy());
  else if (currentPage==='shipping') pg.appendChild(renderShipping());

  // Footer
  const ft = document.createElement('footer');
  ft.style.cssText = 'background:#fff;border-top:1px solid var(--surface-border);padding:56px 24px 32px;margin-top:auto';
  ft.innerHTML = `<div style="max-width:1200px;margin:0 auto">
    <div style="display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:40px;margin-bottom:40px">
      <div>
        <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;font-family:var(--fd);font-size:20px;font-weight:700"><span>🧵</span> Stitched</div>
        <p style="color:var(--text-secondary);font-size:13px;line-height:1.7;max-width:280px">A curated marketplace of authentic goods. We hand-pick every product so you don't have to.</p>
      </div>
      <div>
        <h4 style="font-family:var(--fd);font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:.08em;margin-bottom:12px">Shop</h4>
        <div style="display:flex;flex-direction:column;gap:8px">
          <button class="nav-btn" style="padding:0;font-size:13px" onclick="nav('store')">All Products</button>
          <button class="nav-btn" style="padding:0;font-size:13px" onclick="nav('store');setTimeout(()=>{const i=document.querySelector('#ss');if(i)i.focus()},100)">Search</button>
        </div>
      </div>
      <div>
        <h4 style="font-family:var(--fd);font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:.08em;margin-bottom:12px">Info</h4>
        <div style="display:flex;flex-direction:column;gap:8px">
          <button class="nav-btn" style="padding:0;font-size:13px" onclick="nav('about')">About</button>
          <button class="nav-btn" style="padding:0;font-size:13px" onclick="nav('shipping')">Shipping & Returns</button>
          <button class="nav-btn" style="padding:0;font-size:13px" onclick="nav('terms')">Terms & Conditions</button>
          <button class="nav-btn" style="padding:0;font-size:13px" onclick="nav('privacy')">Privacy Policy</button>
        </div>
      </div>
      <div>
        <h4 style="font-family:var(--fd);font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:.08em;margin-bottom:12px">Support</h4>
        <div style="display:flex;flex-direction:column;gap:8px;font-size:13px;color:var(--text-secondary)">
          <span>contact@stitched.store</span>
          <span>Mon–Fri, 9AM–6PM</span>
        </div>
      </div>
    </div>
    <div style="border-top:1px solid var(--surface-border);padding-top:20px;display:flex;justify-content:space-between;font-size:12px;color:var(--text-muted);flex-wrap:wrap;gap:8px">
      <span>© 2026 Stitched. All rights reserved.</span>
      <span>Made with care.</span>
    </div>
  </div>`;

  app.append(h, pg, ft);
  document.getElementById('cb') && (document.getElementById('cb').textContent=cc);
}

function nav(p) { currentPage=p; render(); }

// ─── Info Pages ──────────────────────────────────────────────────────
function renderAbout() {
  const p = document.createElement('div');
  p.className = 'page';
  p.style.cssText = 'padding:80px 24px;flex:1';
  p.innerHTML = `<div style="max-width:720px;margin:0 auto">
    <button class="btn-secondary" style="margin-bottom:24px" onclick="nav('store')">← Back</button>
    <h1 style="font-family:var(--fd);font-size:clamp(28px,4vw,40px);font-weight:700;letter-spacing:-0.03em;margin-bottom:24px">About Stitched</h1>
    <div style="background:#fff;border:1px solid var(--surface-border);border-radius:var(--radius-xl);padding:32px;box-shadow:var(--shadow-sm);line-height:1.8;color:var(--text-secondary)">
      <p style="margin-bottom:16px;color:var(--text);font-size:16px"><strong>Welcome to Stitched.</strong> We believe great products shouldn't be hard to find.</p>
      <p style="margin-bottom:16px">Stitched is a curated marketplace that brings together quality goods from trusted suppliers around the world. Every item in our catalog has been selected for its value, craftsmanship, and appeal — so you can shop with confidence.</p>
      <p style="margin-bottom:16px">Our model is simple: we partner with reliable suppliers, negotiate fair prices, and pass the savings on to you. No middlemen markups, no questionable listings — just products worth sharing.</p>
      <p style="margin-bottom:16px">We're a small team passionate about making online shopping straightforward and honest. If something doesn't feel right, reach out — we're here to help.</p>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:24px;padding-top:24px;border-top:1px solid var(--surface-border)">
        <div style="text-align:center"><div style="font-size:28px;margin-bottom:4px">🎯</div><div style="font-size:13px;font-weight:600;color:var(--text)">Curated</div><div style="font-size:12px;color:var(--text-muted)">Every product hand-picked</div></div>
        <div style="text-align:center"><div style="font-size:28px;margin-bottom:4px">🤝</div><div style="font-size:13px;font-weight:600;color:var(--text)">Trusted</div><div style="font-size:12px;color:var(--text-muted)">Reliable suppliers only</div></div>
        <div style="text-align:center"><div style="font-size:28px;margin-bottom:4px">💬</div><div style="font-size:13px;font-weight:600;color:var(--text)">Support</div><div style="font-size:12px;color:var(--text-muted)">We're here for you</div></div>
      </div>
    </div>
  </div>`;
  return p;
}

function renderTerms() {
  const p = document.createElement('div');
  p.className = 'page';
  p.style.cssText = 'padding:80px 24px;flex:1';
  p.innerHTML = `<div style="max-width:720px;margin:0 auto">
    <button class="btn-secondary" style="margin-bottom:24px" onclick="nav('store')">← Back</button>
    <h1 style="font-family:var(--fd);font-size:clamp(28px,4vw,40px);font-weight:700;letter-spacing:-0.03em;margin-bottom:24px">Terms & Conditions</h1>
    <div style="background:#fff;border:1px solid var(--surface-border);border-radius:var(--radius-xl);padding:32px;box-shadow:var(--shadow-sm);line-height:1.8;color:var(--text-secondary);font-size:13px">
      <p style="margin-bottom:16px"><strong>Last updated:</strong> July 2026</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">1. Acceptance of Terms</h3>
      <p style="margin-bottom:12px">By accessing or using Stitched, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use our service.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">2. Products & Pricing</h3>
      <p style="margin-bottom:12px">All product descriptions, images, and prices are provided for informational purposes. We make every effort to ensure accuracy, but we do not guarantee that product descriptions or prices are error-free. Prices are subject to change without notice.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">3. Orders & Payment</h3>
      <p style="margin-bottom:12px">When you place an order, you agree to provide accurate and complete information. Payment is due at the time of order. We reserve the right to refuse or cancel any order at our discretion.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">4. Shipping & Delivery</h3>
      <p style="margin-bottom:12px">Shipping times are estimates and not guaranteed. We are not responsible for delays caused by customs, carriers, or unforeseen circumstances. Risk of loss passes to you upon delivery to the carrier.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">5. Returns & Refunds</h3>
      <p style="margin-bottom:12px">Please refer to our Shipping & Returns policy for detailed information on returns and refunds. Generally, items may be returned within 30 days of delivery in unused condition.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">6. Limitation of Liability</h3>
      <p style="margin-bottom:12px">Stitched shall not be liable for any indirect, incidental, or consequential damages arising from your use of this service or any products purchased through it.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">7. Changes</h3>
      <p style="margin-bottom:12px">We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance of the new terms.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">8. Contact</h3>
      <p>For questions about these terms, contact us at <strong>contact@stitched.store</strong>.</p>
    </div>
  </div>`;
  return p;
}

function renderPrivacy() {
  const p = document.createElement('div');
  p.className = 'page';
  p.style.cssText = 'padding:80px 24px;flex:1';
  p.innerHTML = `<div style="max-width:720px;margin:0 auto">
    <button class="btn-secondary" style="margin-bottom:24px" onclick="nav('store')">← Back</button>
    <h1 style="font-family:var(--fd);font-size:clamp(28px,4vw,40px);font-weight:700;letter-spacing:-0.03em;margin-bottom:24px">Privacy Policy</h1>
    <div style="background:#fff;border:1px solid var(--surface-border);border-radius:var(--radius-xl);padding:32px;box-shadow:var(--shadow-sm);line-height:1.8;color:var(--text-secondary);font-size:13px">
      <p style="margin-bottom:16px"><strong>Last updated:</strong> July 2026</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">1. Information We Collect</h3>
      <p style="margin-bottom:12px">We collect information you provide when placing an order: your name, email address, shipping address, and payment details. We also collect anonymous usage data to improve our service.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">2. How We Use Your Information</h3>
      <p style="margin-bottom:12px">We use your information to process orders, communicate with you about your purchases, improve our store, and comply with legal obligations. We do not sell your personal information to third parties.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">3. Data Security</h3>
      <p style="margin-bottom:12px">We implement reasonable security measures to protect your information. However, no method of transmission over the Internet is 100% secure.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">4. Cookies</h3>
      <p style="margin-bottom:12px">We use minimal cookies necessary for the functioning of the store. You can control cookie preferences through your browser settings.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">5. Third Parties</h3>
      <p style="margin-bottom:12px">We may share your information with trusted third parties who help us process payments and deliver orders. These partners are bound by confidentiality agreements.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">6. Your Rights</h3>
      <p style="margin-bottom:12px">You have the right to access, correct, or delete your personal information. To exercise these rights, contact us at <strong>contact@stitched.store</strong>.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">7. Changes</h3>
      <p>We may update this policy. We will notify you of material changes via the website.</p>
    </div>
  </div>`;
  return p;
}

function renderShipping() {
  const p = document.createElement('div');
  p.className = 'page';
  p.style.cssText = 'padding:80px 24px;flex:1';
  p.innerHTML = `<div style="max-width:720px;margin:0 auto">
    <button class="btn-secondary" style="margin-bottom:24px" onclick="nav('store')">← Back</button>
    <h1 style="font-family:var(--fd);font-size:clamp(28px,4vw,40px);font-weight:700;letter-spacing:-0.03em;margin-bottom:24px">Shipping & Returns</h1>
    <div style="background:#fff;border:1px solid var(--surface-border);border-radius:var(--radius-xl);padding:32px;box-shadow:var(--shadow-sm);line-height:1.8;color:var(--text-secondary);font-size:13px">
      <h3 style="color:var(--text);margin:0 0 8px;font-size:15px">Shipping</h3>
      <p style="margin-bottom:12px">We offer worldwide shipping on all orders. Standard shipping takes 7–14 business days depending on your location. Express shipping options are available at checkout.</p>
      <p style="margin-bottom:16px"><strong>Free shipping</strong> on all orders over $50.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">Order Tracking</h3>
      <p style="margin-bottom:16px">Once your order ships, you'll receive a tracking number via email. You can check your order status anytime from your account or by contacting us.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">Returns</h3>
      <p style="margin-bottom:12px">We accept returns within <strong>30 days</strong> of delivery. Items must be unused and in original packaging. To initiate a return, email <strong>contact@stitched.store</strong> with your order number.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">Refunds</h3>
      <p style="margin-bottom:12px">Refunds are processed within 5–7 business days after we receive the returned item. The refund will be issued to the original payment method. Shipping costs are non-refundable.</p>
      <h3 style="color:var(--text);margin:20px 0 8px;font-size:15px">Damaged or Incorrect Items</h3>
      <p>If you receive a damaged or incorrect item, contact us within 48 hours of delivery. We'll arrange a replacement or full refund, including return shipping costs.</p>
    </div>
  </div>`;
  return p;
}

// ─── Store Page ──────────────────────────────────────────────────────
function renderStore() {
  const page = document.createElement('div');
  let search = '', cat = 'all';
  const cats = ['all',...new Set(products.map(p=>p.category))];

  function grid() {
    const g = page.querySelector('.pg');
    if (!g) return;
    const flt = products.filter(p => {
      if (cat!='all' && p.category!==cat) return false;
      if (search && !p.name.toLowerCase().includes(search.toLowerCase())) return false;
      return true;
    });
    g.innerHTML = flt.length === 0
      ? '<div class="empty-state"><span class="empty-state-icon">📦</span><p>No products</p></div>'
      : flt.map(p => `<div class="pc" onclick="navProduct('${p.id}')">
          <div class="pc-img"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.src='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22300%22 height=%22300%22><rect fill=%22%23f0efe8%22 width=%22300%22 height=%22300%22/><text fill=%22%23a8a7b2%22 font-size=%2240%22 x=%22150%22 y=%22160%22 text-anchor=%22middle%22>📦</text></svg>'"></div>
          <div class="pc-info">
            <span class="pc-cat">${p.category}</span>
            <h3 class="pc-name">${p.name}</h3>
            <p class="pc-desc">${(p.description||'').slice(0,80)}${(p.description||'').length>80?'…':''}</p>
            <div class="pc-row">
                <span class="pc-price">$${p.yourPrice.toFixed(2)}</span>
                <span class="pc-old" style="display:none">$${p.supplierPrice.toFixed(2)}</span>
                ${p.rating ? `<span class="pc-rating">★ ${p.rating}</span>` : ''}
            </div>
          </div>
        </div>`).join('');
  }

  page.innerHTML = `
    <section class="hero">
      <div class="hero-badge"><span class="hero-badge-dot"></span> Curated Collection</div>
      <h1>Products worth<br>sharing.</h1>
      <p class="hero-sub">A curated marketplace of authentic goods. Browse, add to cart, and manage everything from one dashboard.</p>
      <div class="hero-actions">
        <button class="btn-primary" onclick="nav('admin')">Dashboard</button>
        <button class="btn-secondary" onclick="document.querySelector('.sec')?.scrollIntoView({behavior:'smooth'})">Explore →</button>
      </div>
      <div class="hero-stats">
        <div class="hero-stat"><div class="hero-stat-num">${products.length}</div><div class="hero-stat-label">Products</div></div>
        <div class="hero-stat"><div class="hero-stat-num">${orders.length}</div><div class="hero-stat-label">Orders</div></div>
      </div>
    </section>
    <section class="sec" style="padding:40px 24px 80px;max-width:1200px;margin:0 auto;width:100%">
      <div class="sec-h">
        <div>
          <div class="sec-label">Products</div>
          <h2 style="font-family:var(--fd);font-size:clamp(24px,3.5vw,36px);font-weight:700;letter-spacing:-0.03em">Featured Products</h2>
        </div>
        <div class="sec-ctrl">
          <div class="sw"><svg class="si" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>
            <input class="si-i" type="text" placeholder="Search..." id="ss"></div>
          <div class="cf" id="cf">${cats.map(c=>`<button class="cf-btn ${c===cat?'active':''}" data-c="${c}">${c==='all'?'All':c}</button>`).join('')}</div>
        </div>
      </div>
      <div class="pg"></div>
    </section>`;

  grid();
  setTimeout(() => {
    const inp = page.querySelector('#ss');
    if (inp) inp.oninput = function() { search=this.value; grid(); };
    page.querySelectorAll('#cf .cf-btn').forEach(b => {
      b.onclick = function() {
        page.querySelectorAll('#cf .cf-btn').forEach(x => x.classList.remove('active'));
        this.classList.add('active'); cat = this.dataset.c; grid();
      };
    });
  }, 0);
  return page;
}

// ─── Product Detail Page ─────────────────────────────────────────────
function renderProduct() {
  const pid = sessionStorage.getItem('st_pid') || '';
  const p = products.find(x => x.id === pid);
  if (!p) { currentPage='store'; return renderStore(); }

  const page = document.createElement('div');
  page.className = 'page';
  page.style.padding = '40px 24px';

  const imgs = p.images || [p.image];
  page.innerHTML = `
    <div style="max-width:1000px;margin:0 auto;width:100%">
      <button class="btn-secondary" style="margin-bottom:24px" onclick="nav('store')">← Back</button>
      <div class="pd-layout">
        <div class="pd-gallery">
          <div class="pd-main"><img src="${imgs[0]}" alt="${p.name}" id="pdMain" onerror="this.outerHTML='<div style=\\'height:400px;display:flex;align-items:center;justify-content:center;font-size:64px\\'>📦</div>'"></div>
          <div class="pd-thumbs">${imgs.slice(0,4).map((u,i) => `<img src="${u}" class="pd-thumb ${i===0?'active':''}" onclick="document.getElementById('pdMain').src=this.src;document.querySelectorAll('.pd-thumb').forEach(t=>t.classList.remove('active'));this.classList.add('active')">`).join('')}</div>
        </div>
        <div class="pd-info">
          <span class="pc-cat">${p.category}</span>
          <h1 class="pd-title">${p.name}</h1>
          ${p.rating ? `<div style="color:var(--accent);font-size:14px;margin:4px 0">★ ${p.rating} / 5</div>` : ''}
          <p class="pd-desc">${p.description}</p>
          <div class="pd-prices">
            <span class="pd-price">$${p.yourPrice.toFixed(2)}</span>
          </div>
          <button class="btn-primary" style="width:100%;margin-top:16px" onclick="addCart('${p.id}');nav('store')">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>
            Add to Cart — $${p.yourPrice.toFixed(2)}
          </button>
        </div>
      </div>
    </div>`;
  page.style.cssText += `padding:40px 24px;flex:1;max-width:1000px;margin:0 auto;width:100%`;
  return page;
}

function navProduct(id) { sessionStorage.setItem('st_pid', id); nav('product'); }

// ─── Cart ─────────────────────────────────────────────────────────────
function addCart(id) {
  const p = products.find(x => x.id === id);
  if (!p) return;
  const e = cart.find(i => i.id === id);
  if (e) e.qty++;
  else cart.push({ id, name: p.name, price: p.yourPrice, qty:1, image: p.image });
  lssj('cart', cart);
  notify('Added ✓');
  const b = document.getElementById('cb');
  if (b) { const c = cart.reduce((s,i) => s+i.qty, 0); b.textContent = c; b.classList.toggle('hidden', c===0); }
}

function cartQty(id, d) {
  cart = cart.map(i => i.id===id ? {...i, qty: Math.max(0,i.qty+d)} : i).filter(i => i.qty>0);
  lssj('cart', cart);
  const ov = document.querySelector('.co');
  if (ov) { ov.remove(); cartOpen(); }
  render();
}

function cartOpen() {
  const e = document.querySelector('.co');
  if (e) { e.classList.toggle('open'); return; }
  const d = document.createElement('div');
  d.className = 'co open';
  const ct = cart.reduce((s,i) => s+i.price*i.qty, 0);
  d.innerHTML = `<div class="cp">
    <div class="cph"><h3>Cart</h3><button class="close-btn" onclick="cartClose()">✕</button></div>
    ${cart.length===0 ? '<div class="empty-state" style="padding:32px">Empty</div>' : `
      <div class="ci">${cart.map(i => `
        <div class="ci-row">
          <div class="ci-info">
            <img src="${i.image}" width="36" height="36" style="border-radius:6px;object-fit:cover">
            <div><div class="ci-name">${i.name}</div><div class="ci-p">$${i.price.toFixed(2)}</div></div>
          </div>
          <div class="ci-qty">
            <button class="qty-btn" onclick="cartQty('${i.id}',-1)">−</button>
            <span class="qty-n">${i.qty}</span>
            <button class="qty-btn" onclick="cartQty('${i.id}',1)">+</button>
          </div>
        </div>`).join('')}</div>
      <div class="ctot"><span>Total</span><span style="color:var(--accent)">$${ct.toFixed(2)}</span></div>
      <button class="btn-primary" style="width:100%" onclick="cartClose();nav('checkout')">Checkout</button>
    `}
  </div>`;
  d.onclick = function(ev) { if (ev.target===this) this.classList.remove('open'); };
  document.body.appendChild(d);
}
function cartClose() { document.querySelector('.co')?.classList.remove('open'); }

// ─── Checkout ─────────────────────────────────────────────────────────
function renderCheckout() {
  if (cart.length === 0) {
    const p = document.createElement('div');
    p.style.cssText='display:flex;align-items:center;justify-content:center;min-height:60vh';
    p.innerHTML = '<div class="empty-state"><span class="empty-state-icon">🛒</span><h3 style="margin:8px 0;font-family:var(--fd)">Cart empty</h3><button class="btn-primary" onclick="nav(\'store\')">Browse</button></div>';
    return p;
  }
  const ct = cart.reduce((s,i) => s+i.price*i.qty, 0);
  const p = document.createElement('div'); p.className='checkout-page';
  p.innerHTML = `
    <div class="co-layout">
      <div class="co-form">
        <h2>Checkout</h2>
        <div class="sb"><h4>Shipping</h4>
          <div class="ff"><label>Full Name</label><input type="text" id="cn"></div>
          <div class="ff"><label>Email</label><input type="email" id="ce"></div>
          <div class="ff"><label>Address</label><textarea id="ca" rows="3"></textarea></div>
        </div>
        <div class="sb"><h4>Payment</h4><p class="pn">🔒 Test mode — no real charges</p>
          <div class="ff"><label>Card</label><input type="text" inputmode="numeric" id="cc" placeholder="4242 4242 4242 4242" maxlength="19"></div>
          <div class="cr"><div class="ff"><label>Expiry</label><input type="text" inputmode="numeric" id="cex" placeholder="MM/YY" maxlength="5"></div>
          <div class="ff"><label>CVC</label><input type="text" inputmode="numeric" id="cvc" placeholder="123" maxlength="4"></div></div>
        </div>
        <button class="btn-primary" style="width:100%;padding:14px" onclick="placeOrder()" id="pb">Pay $${ct.toFixed(2)}</button>
      </div>
      <div class="co-summary">
        <h4>Order Summary</h4>
        ${cart.map(i => `<div class="sum-item"><span>${i.name} × ${i.qty}</span><span>$${(i.price*i.qty).toFixed(2)}</span></div>`).join('')}
        <div class="sum-total"><span>Total</span><span>$${ct.toFixed(2)}</span></div>
      </div>
    </div>`;
  return p;
}

function placeOrder() {
  const n = document.getElementById('cn')?.value;
  const e = document.getElementById('ce')?.value;
  const a = document.getElementById('ca')?.value;
  if (!n||!e||!a) return notify('Fill in all details');
  const btn = document.getElementById('pb');
  btn.disabled = true; btn.textContent = '⏳ Processing…';
  setTimeout(() => {
    const ct = cart.reduce((s,i) => s+i.price*i.qty, 0);
    orders.unshift({ id:crypto.randomUUID(), customerName:n, customerEmail:e, shippingAddress:a, items:[...cart], total:ct, status:'pending', createdAt:new Date().toISOString() });
    lssj('orders', orders);
    cart = []; lssj('cart', cart);
    nav('confirmed');
    notify('Order placed ✓');
  }, 1200);
}

function renderConfirmed() {
  const p = document.createElement('div'); p.className='confirmed-page';
  p.innerHTML = '<div class="cc"><span class="confirmed-icon">✅</span><h2>Order Placed!</h2><p>Check Dashboard to fulfill.</p><button class="btn-primary" onclick="nav(\'store\')">Continue</button></div>';
  return p;
}

// ─── Dashboard ────────────────────────────────────────────────────────
function renderDash() {
  const p = document.createElement('div'); p.className='dashboard';
  const pen = orders.filter(o => o.status === 'pending').length;
  const rev = orders.reduce((s,o) => s+o.total, 0);
  let tab = 'orders';

  function content() {
    const c = p.querySelector('.dbc');
    if (!c) return;
    if (tab === 'orders') {
      c.innerHTML = orders.length === 0
        ? '<div class="empty-state"><span class="empty-state-icon">📋</span><p>No orders yet</p></div>'
        : `<div class="ol">${orders.map(o => `
          <div class="oc ${o.status}">
            <div class="oh"><div><span class="oi">#${o.id.slice(0,8)}</span> <span class="os ${o.status}">${o.status}</span></div><span class="odate">${new Date(o.createdAt).toLocaleDateString()}</span></div>
            <div class="ocust">${o.customerName} · ${o.customerEmail}</div>
            <div class="oship">📍 ${o.shippingAddress}</div>
            <div style="font-size:12px;color:var(--text-secondary);margin:6px 0">${o.items.map(i => `<div class="sum-item"><span>${i.name} × ${i.qty}</span><span>$${(i.price*i.qty).toFixed(2)}</span></div>`).join('')}</div>
            <div class="of"><span class="ot">$${o.total.toFixed(2)}</span>${o.status==='pending'?`<button class="fb" onclick="fulfill('${o.id}')">Mark Fulfilled</button>`:''}</div>
          </div>`).join('')}</div>`;
    } else {
      c.innerHTML = `
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
          <span style="font-size:13px;color:var(--text-secondary)">${products.length} products</span>
          <button class="btn-primary" style="padding:8px 18px;font-size:12px" onclick="showPF()">+ Add Product</button>
        </div>
        <div id="pf" class="pf hidden">
          <h4>New Product</h4>
          <div class="fg"><div class="ff"><label>Name</label><input id="pfn"></div>
          <div class="ff"><label>Category</label><select id="pfc"><option>Electronics</option><option>Clothing</option><option>Home</option><option>Accessories</option><option>Beauty</option><option>Other</option></select></div>
          <div class="ff" style="grid-column:1/-1"><label>Image URL</label><input id="pfi" placeholder="https://..."></div>
          <div class="ff" style="grid-column:1/-1"><label>Description</label><input id="pfd"></div>
          <div class="ff"><label>Supplier Price ($)</label><input type="number" step="0.01" id="pfsp"></div>
          <div class="ff"><label>Your Price ($)</label><input type="number" step="0.01" id="pfyp"></div></div>
          <button class="submit-btn" onclick="submitP()">Add</button>
        </div>
        <div class="ptw"><table class="pt"><thead><tr><th>Product</th><th>Cost</th><th>Sell</th><th>Profit</th><th></th></tr></thead>
          <tbody>${products.map(p => {
            const profit = p.yourPrice - p.supplierPrice;
            return `<tr><td><div style="display:flex;align-items:center;gap:8px"><img src="${p.image}" width="32" height="32" style="border-radius:4px;object-fit:cover"><div><strong>${p.name}</strong><br><span style="font-size:11px;color:var(--text-muted)">${p.category}</span></div></div></td>
              <td>$${p.supplierPrice.toFixed(2)}</td>
              <td>$${p.yourPrice.toFixed(2)}</td>
              <td class="profit">+$${profit.toFixed(2)}</td>
              <td class="dc"><button class="db" onclick="delP('${p.id}')"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></td></tr>`;
          }).join('')}</tbody></table></div>`;
    }
  }

  p.innerHTML = `
    <div class="dh"><h2>Dashboard</h2>
      <div class="ds"><div class="sc"><div class="scl">Products</div><div class="scv">${products.length}</div></div>
      <div class="sc accent"><div class="scl">Revenue</div><div class="scv">$${rev.toFixed(2)}</div></div>
      <div class="sc"><div class="scl">Orders</div><div class="scv">${orders.length}</div></div>
      <div class="sc"><div class="scl">To Fulfill</div><div class="scv">${pen}</div></div></div>
      <div class="dt"><button class="dt-btn ${tab==='orders'?'active':''}" onclick="switchDT('orders')">Orders</button>
      <button class="dt-btn ${tab==='products'?'active':''}" onclick="switchDT('products')">Products</button></div>
    </div>
    <div class="dbc"></div>`;

  content();
  return p;
}

window.fulfill = function(id) {
  const o = orders.find(x => x.id === id);
  if (o) { o.status='fulfilled'; lssj('orders', orders); notify('Fulfilled ✓'); render(); }
};
window.switchDT = function(t) {
  const d = document.querySelector('.dashboard');
  if (!d) return;
  const c = d.querySelector('.dbc');
  if (!c) return;
  // Redraw
  render();
};
window.showPF = function() { document.getElementById('pf')?.classList.toggle('hidden'); };
window.submitP = function() {
  const n = document.getElementById('pfn')?.value;
  const yp = parseFloat(document.getElementById('pfyp')?.value);
  if (!n||!yp) return notify('Name and price required');
  products.push({
    id: crypto.randomUUID(), name: n, description: document.getElementById('pfd')?.value||'',
    category: document.getElementById('pfc')?.value||'Other', supplier: 'Manual',
    supplierPrice: parseFloat(document.getElementById('pfsp')?.value)||0,
    yourPrice: yp, image: document.getElementById('pfi')?.value||'', images: [],
  });
  lssj('products', products); notify('Added ✓'); render();
};
window.delP = function(id) {
  products = products.filter(p => p.id !== id);
  lssj('products', products); notify('Deleted'); render();
};

// ─── Boot ─────────────────────────────────────────────────────────────
init();
